# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        UsuariosBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
                # users:
                #     avia:
                #         password: avia
                #         roles: 'ROLE_USER'
                #     admin:
                #         password: fistandantilus
                #         # roles: 'ROLE_ADMIN'
        my_db_provider:
            entity:
                class: UsuariosBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Etiqueta
        # pattern: ^/ruta -> indica la carpeta donde tiene ámbito el logeado.
        # provider : -> según decladaro arriba
        # form_login:
            # login_path: Nombre de la acción para el logeado
            # check_path: Nombre de la accion para verificar el logueado -> Pueden ser la misma
        usuarios:
          pattern: ^/
          anonymous: ~

          provider: my_db_provider
          #indicamos la ruta del login y logout
          form_login:
              login_path: /login
              check_path: /login
              username_parameter: _username
              target_path_parameter: go_to

          logout:
              path: /logout
              target: /
        main:
            #anonymous: ~
            http_basic: ~

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles:[ROLE_CANDIDATO, ROLE_EDITOR, ROLE_ADMIN] }
