<?php

namespace OfertasBundle\Repository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConocimientosRepository extends \Doctrine\ORM\EntityRepository
{
}
