<?php

namespace OfertasBundle\Repository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoRepository extends \Doctrine\ORM\EntityRepository
{
}
