<?php

namespace OfertasBundle\Repository;

/**
 * JornadaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JornadaLaboralRepository extends \Doctrine\ORM\EntityRepository
{
}
