<?php

namespace OfertasBundle\Repository;

/**
 * ProvinciasOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciasOfertaRepository extends \Doctrine\ORM\EntityRepository
{
}
