<?php

namespace EmpresasBundle\Repository;

/**
 * BusquedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusquedaRepository extends \Doctrine\ORM\EntityRepository
{
}
